world-federation-of-advertisers/common-jvm

.github/workflows/build-test.yml
.github/workflows/lint.yml
.gitignore
.lintignore
AUTHORS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/2)

Add Cross-Media Measurement repo boilerplate

---

.editorconfig
WORKSPACE
imports/kotlin/com/nhaarman/mockitokotlin2/BUILD.bazel
imports/kotlin/org/mockito/kotlin/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/testing/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/testing/MockitoUtils.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/4)

Switch from com.nhaarman.mockitokotlin2 to org.mockito.kotlin

---

src/main/kotlin/org/wfanet/measurement/common/Filters.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerStructs.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/9)

Add EqualClause for db filters

---

build/io_bazel_rules_kotlin/repo.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/11)

Update rules_kotlin to v1.5.0-beta-2.

---

src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/TlsFlags.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/17)

Extract the tls flags into a separate class.

---

src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/TlsFlags.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/TransportSecurity.kt
src/main/kotlin/org/wfanet/measurement/storage/forwarded/ForwardedStorageFromFlags.kt
src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/16)

Add a method to build a channel with client certs.

---

src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/18)

Override authority when building mTLS and TLS channels.

---

src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/DateUtil.kt
src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/DateUtilTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/22)

Move DateUtil into common repo

---

WORKSPACE
build/common_jvm_deps.bzl
build/common_jvm_extra_deps.bzl
build/common_jvm_maven.bzl
build/common_jvm_repositories.bzl

Move Maven deps from WORKSPACE to bzl files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/23)

Move Maven from WORKSPACE to bzl files

---

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/25)

Add Mutation helpers to buffer to a TransactionContext

---

build/io_bazel_rules_kotlin/repo.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/28)

Map kotlib stdlib-common to @com_github_jetbrains_common

---

src/main/proto/google/type/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/30)

Add kt_jvm_proto_library target for google.type.Date

---

src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/grpc/testing/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/testing/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/throttler/testing/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/storage/filesystem/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/storage/forwarded/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/storage/testing/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/identity/IdentifiersTest.kt
src/test/kotlin/org/wfanet/measurement/common/throttler/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/storage/filesystem/BUILD.bazel
src/test/proto/wfa/measurement/common/BUILD.bazel

This adds deps to targets to try to maintain strict deps. Also removes a few unneeded deps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/31)

Add missing dependencies.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/crypto/Hashing.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/crypto/HashingTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/32)

Add a hashSha256 method to common-jvm.

---

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Mutations.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Statements.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Structs.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/33)

Add InternalId/ExternalId overloads for Spanner value binding.

---

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Statements.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Structs.kt
src/test/kotlin/org/wfanet/measurement/gcloud/spanner/StatementsTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/36)

Remove unused, deprecated Spanner builders.

---

src/main/kotlin/org/wfanet/measurement/common/Bytes.kt
src/main/kotlin/org/wfanet/measurement/common/HexString.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/35)

Add HexString data class for stronger typing of hexadecimal strings.

---

src/main/kotlin/org/wfanet/measurement/storage/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/storage/Store.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/37)

Add abstract Store class for blob stores.

---

src/main/kotlin/org/wfanet/measurement/storage/testing/InMemoryStorageClient.kt

- Will follow up with a similar change removing from panel-exchange-client
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/38)

Move InMemoryStorageClient from panel-exchange-client

---

build/io_bazel_rules_docker/base_images.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/39)

Update java base images to use Debian 11 nonroot images

---

src/main/kotlin/org/wfanet/measurement/common/throttler/Throttler.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/41)

Yield in Throttler.loopOnReady

---

src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/PrivateKeyStore.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/49)

Implement all TODOs for Tink skeletons

---

build/com_google_protobuf/repo.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/53)

Update protobuf to 3.19.1.

---

src/main/kotlin/org/wfanet/measurement/storage/Store.kt

The blob key works like a resource name, which has no leading slash in
the beginning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/54)

Don't add slash in the beginning of the blob key.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/Hashing.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/HashingTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/55)

Add function to compute SHA-256 hashes of Long values.

---

build/common_jvm_maven.bzl
imports/java/com/google/cloud/bigquery/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/56)

Add the google cloud bigquery to common imports

---

build/common_jvm_deps.bzl
build/common_jvm_repositories.bzl
build/io_bazel_rules_go/deps.bzl
build/io_bazel_rules_go/repo.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/57)

Update rules_go to 0.29.0, using a fixed Go SDK version.

---

src/main/kotlin/org/wfanet/measurement/common/throttler/MinimumIntervalThrottler.kt

It was using a negative value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/60)

Fix a bug that delay is not doing anything.

---

build/kt_jvm_proto_library.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/59)

Use jar util from Java runtime rather than zipper to create srcjar.

---

src/main/kotlin/org/wfanet/measurement/common/throttler/MinimumIntervalThrottler.kt

The while loop is redundant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/61)

Delay the expected duration if positive or 0.

---

.editorconfig
src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/62)

Add Kotlin convenience function to generate KeyPairs

---

src/main/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/67)

Add factory for generating Tink ECIES key pairs.

---

WORKSPACE
build/common_jvm_maven.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/71)

Exclude log4j explicitly while we investigate log4shell

---

build/common_jvm_maven.bzl
imports/java/com/adobe/testing/s3mock/junit4/BUILD.bazel
imports/java/software/amazon/awssdk/core/BUILD.bazel
imports/java/software/amazon/awssdk/http/BUILD.bazel
imports/java/software/amazon/awssdk/services/s3/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/aws/s3/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt
src/main/kotlin/org/wfanet/measurement/common/Bytes.kt
src/test/kotlin/org/wfanet/measurement/aws/s3/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/aws/s3/S3StorageClientTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/68)

Add S3StorageClient

---

src/main/kotlin/org/wfanet/measurement/storage/testing/InMemoryStorageClient.kt
src/test/kotlin/org/wfanet/measurement/storage/testing/InMemoryStorageClientTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/76)

Expose contents of InMemoryStorageClient

---

src/main/kotlin/org/wfanet/measurement/common/openid/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/78)

Change visibility of request uri helper.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwkHandle.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/VerifiedJwt.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokensTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/79)

Wrap jwt verifier and verified jwt.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/tink/JwkHandle.kt

…er issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/81)

Add tink jwt registering to PublicJwkHandle to fix class load order issue

---

src/main/kotlin/org/wfanet/measurement/common/ProtoUtils.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/91)

add type registry to parseTextProto

---

src/main/kotlin/org/wfanet/measurement/common/grpc/Preconditions.kt
src/test/kotlin/org/wfanet/measurement/common/grpc/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/grpc/PreconditionsTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/95)

Update argument list of failGrpc() to include the cause of error

---

src/main/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/crypto/PemIo.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/97)

Add PublicKey to PemWriter and make it public

---

src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt
src/main/kotlin/org/wfanet/measurement/gcloud/gcs/GcsStorageClient.kt
src/main/kotlin/org/wfanet/measurement/storage/StorageClient.kt
src/main/kotlin/org/wfanet/measurement/storage/Store.kt
src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageClient.kt
src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageService.kt
src/main/kotlin/org/wfanet/measurement/storage/forwarded/ForwardedStorageClient.kt
src/main/kotlin/org/wfanet/measurement/storage/testing/AbstractStorageClientTest.kt
src/main/kotlin/org/wfanet/measurement/storage/testing/InMemoryStorageClient.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/93)

Ensure StorageClient RPCs/IO occurs in Dispatchers.IO.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/KeyStorageProvider.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/PrivateKeyStore.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/SigningKeyStore.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/PrivateKeyStore.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyStorageProvider.kt
src/main/kotlin/org/wfanet/measurement/storage/Store.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/SigningKeyStoreTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/94)
https://rally1.rallydev.com/#/?detail=/task/625602588885&fdp=true

Deterministically derive blob keys from Store context.

---

src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/SpannerEmulatorMain.kt

fixes encoding of the hash to match how amazon computes it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/108)

s3client fixes

---

build/com_github_grpc_grpc_kotlin/repo.bzl
build/com_google_protobuf/repo.bzl
build/common_jvm_maven.bzl
build/tink/repo.bzl
build/versions.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/114)

Ensure common_jvm_maven_artifacts includes artifacts from grpc-java.

---

src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt
src/main/kotlin/org/wfanet/measurement/storage/testing/AbstractStorageClientTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/118)

fix bug in s3client for empty blobs

---

build/common_jvm_maven.bzl
imports/java/com/opentable/db/postgres/BUILD.bazel
imports/java/liquibase/ext/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/Uris.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/DatabaseClient.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/QueryResult.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/ReadContext.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/ReadWriteContext.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/StatementBuilder.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/StatementResult.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresDatabaseClient.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/testing/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/testing/EmbeddedPostgresDatabaseProvider.kt
src/main/proto/google/type/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresDatabaseClientTest.kt
src/test/resources/db/postgres/BUILD.bazel
src/test/resources/db/postgres/changelog.yaml
src/test/resources/db/postgres/create-test-schema.sql

This encapsulates usage of Reactive Streams.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/125)

Add a DatabaseClient which wraps R2DBC connections.

---

src/main/kotlin/org/wfanet/measurement/common/ProtoUtils.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/Signatures.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/RpcStatus.kt
src/main/kotlin/org/wfanet/measurement/common/throttler/AdaptiveThrottler.kt
src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageServer.kt
src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageService.kt
src/test/kotlin/org/wfanet/measurement/common/FlowKtTest.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClientTest.kt
src/test/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresDatabaseClientTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/129)

Reformat all Kotlin files with ktfmt 0.38.

---

src/main/kotlin/org/wfanet/measurement/common/Reflect.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/BoundStatement.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/QueryResult.kt
src/test/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresDatabaseClientTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/133)

Preserve nullability in R2DBC wrapper.

---

src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/BoundStatement.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/QueryResult.kt
src/main/proto/google/type/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresDatabaseClientTest.kt
src/test/resources/db/postgres/create-test-schema.sql

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/136)

Add bindings for protobuf enums to R2DBC client.

---

build/common_jvm_maven.bzl
imports/java/org/apache/commons/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/137)

Add apache commons-math3 for discrete Laplace random value

---

src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/BoundStatement.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/ReadWriteContext.kt
src/test/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresDatabaseClientTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/139)

Support adding additional bindings when building BoundStatement.

---

src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresConnectionFactories.kt
src/main/kotlin/org/wfanet/measurement/gcloud/postgres/PostgresFlags.kt
src/main/kotlin/org/wfanet/measurement/gcloud/postgres/tools/UpdateSchema.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/142)

Remove unneeded gcloud postgres password flag

---

src/main/kotlin/org/wfanet/measurement/gcloud/postgres/tools/UpdateSchema.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/144)

Fix incorrect Cloud SQL connection settings for UpdateSchema.

---

build/openssl/BUILD.bazel
build/openssl/defs.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/143)

Support multiple hostnames in generate_user_certificate macro.

---

src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageClient.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/149)

Buffer FileSystemStorageClient writes using BufferedOutputStream.

---

build/kotlinx_coroutines/repo.bzl
imports/kotlin/kotlinx/coroutines/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/gcloud/common/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/150)

Remove runBlocking usage in Spanner AsyncDatabaseClient.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/testing/TestData.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/152)

Creating separate val to resolve ca.key file

---

build/common_jvm_maven.bzl
imports/java/com/opencsv/BUILD.bazel

Add OpenCSV library for CsvEventQuery in CMMS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/156)

Add OpenCSV for CsvEventQuery

---

build/kotlinx_coroutines/repo.bzl
imports/kotlin/kotlinx/coroutines/guava/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/gcloud/common/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/Spanner.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerDatabaseConnector.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/SpannerEmulator.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/SpannerEmulatorDatabaseRule.kt

Reverts #155 by re-applying #150 with fixes.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/154)

Remove runBlocking usage in Spanner AsyncDatabaseClient

---

build/common_jvm_maven.bzl
build/kotlinx_coroutines/repo.bzl
imports/java/software/amazon/awssdk/core/BUILD.bazel
imports/java/software/amazon/awssdk/http/BUILD.bazel
imports/kotlin/kotlinx/coroutines/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/aws/s3/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/Hashing.kt
src/test/kotlin/org/wfanet/measurement/aws/s3/S3StorageClientTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/159)

Use S3AsyncClient instead of S3Client.

---

build/common_jvm_maven.bzl
build/rules_kotlin/deps.bzl
build/rules_kotlin/repo.bzl
build/versions.bzl
imports/java/org/jetbrains/annotations/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/Bytes.kt
src/main/kotlin/org/wfanet/measurement/common/Flow.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/PemIo.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/PrivateKeyStore.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyStorageProvider.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt
src/main/kotlin/org/wfanet/measurement/common/testing/JobCloser.kt
src/main/kotlin/org/wfanet/measurement/gcloud/gcs/GcsStorageClient.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/SpannerEmulator.kt
src/main/kotlin/org/wfanet/measurement/storage/filesystem/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageClient.kt
src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageServer.kt
src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageService.kt
src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt
src/test/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageServiceTest.kt

This includes using a fixed thread pool Executor for gRPC servers. It allows more control over thread usage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/160)

Allow CoroutineContexts and Executors to be specified/configured.

---

src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/ReadContext.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/ReadWriteContext.kt
src/test/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresDatabaseClientTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/166)

Add rollbackTransaction to R2DBC context

---

src/main/kotlin/org/wfanet/measurement/common/ContinuationCompletionHandler.kt
src/main/kotlin/org/wfanet/measurement/common/SuspendingByteChannel.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/169)

Implement suspending wrapper for AsynchronousByteChannel.

---

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/SpannerTestingFunctions.kt
src/test/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/PostgresDatabaseClientTest.kt
src/test/kotlin/org/wfanet/measurement/common/graphviz/DotTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/171)

Reformat Kotlin files with ktfmt v0.41.

---

src/main/kotlin/org/wfanet/measurement/common/CommandLines.kt
src/main/kotlin/org/wfanet/measurement/common/ProtoUtils.kt
src/test/kotlin/org/wfanet/measurement/common/ProtoUtilsTest.kt
src/test/kotlin/org/wfanet/measurement/common/testing/CommandLineTestingTest.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/174)

Fix command line duration parsing

---

build/cloud_spanner_emulator/defs.bzl
build/versions.bzl

This allows reuse in places that need consistent versioning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/177)

Extract VersionedArchiveInfo for Spanner emulator.

---

src/main/kotlin/org/wfanet/measurement/common/LocalDateProgression.kt
src/main/kotlin/org/wfanet/measurement/common/OpenEndTimeRange.kt
src/main/kotlin/org/wfanet/measurement/common/ProtoReflection.kt
src/main/proto/wfa/measurement/common/testing/BUILD.bazel
src/main/proto/wfa/measurement/common/testing/depends_on_simple.proto
src/main/proto/wfa/measurement/common/testing/simple.proto
src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/LocalDateProgressionTest.kt
src/test/kotlin/org/wfanet/measurement/common/OpenEndTimeRangeTest.kt
src/test/kotlin/org/wfanet/measurement/common/ProtoReflectionTest.kt

This also adds tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/180)

Copy files in common package from cross-media-measurement repo.

---

src/main/kotlin/org/wfanet/measurement/common/Flow.kt
src/main/kotlin/org/wfanet/measurement/common/ResourceNameParser.kt
src/main/kotlin/org/wfanet/measurement/common/Runfiles.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdTokens.kt
src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/BoundStatement.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt
src/main/kotlin/org/wfanet/measurement/common/testing/MockitoUtils.kt

This is a fully automated change with no manual edits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/181)

Reformat Kotlin source files with ktfmt v0.43.

---

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt

Due to the fact that TransactionScope implemented CoroutineScope, it would be incorrect to use TransactionScope as a receiver for suspending helper functions (see the SuspendFunctionOnCoroutineScope warning). Dropping the type prevents that from occurring.

Drop TransactionScope, passing TransactionContext as parameter instead.

---

build/common_jvm_maven.bzl
build/rules_jvm_external/repo.bzl
build/rules_proto/repo.bzl
build/versions.bzl
imports/java/com/google/protobuf/BUILD.bazel
imports/java/com/google/protobuf/util/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/gcloud/spanner/BUILD.bazel

See world-federation-of-advertisers/cross-media-measurement#884

Update rules_jvm_external to 5.1

---

build/rules_oci/defs.bzl

This fixes an issue where runfiles cannot be loaded from non-leaf repos.

Include repo mapping manifest in java_image.

---

imports/kotlin/com/google/type/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/ProtoReflection.kt
src/test/kotlin/org/wfanet/measurement/common/ProtoReflectionTest.kt

This also exposes ProtoReflection.buildFileDescriptors.

Include common types from google.type package in WELL_KNOWN_TYPES.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyId.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/TinkKeyIdTest.kt

Update TinkKeyId into an unique id as Long.

---

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt

This will allow index-only reads.

Add readUsingIndex to Spanner AsyncDatabaseClient.

---

MODULE.bazel
MODULE.bazel.lock

This results in io.netty:netty-codec-http2 being updated to at least 4.1.100.Final.

Update grpc-java to 1.60.2.

---

build/rules_oci/defs.bzl

These files are extraneous:
* JDK files are in the base image.
* Dependencies are included in the deploy (AKA "fat") JAR.

Exclude JDK files and dependency JARs from java_image.

---

src/main/kotlin/org/wfanet/measurement/common/db/liquibase/Liquibase.kt

This addresses an issue introduced in #245 that could prevent Spanner JDBC connections from being closed.

Ensure Liquibase Database gets closed.

---

src/main/kotlin/org/wfanet/measurement/common/NativeLibraryLoader.kt

Add NativeLibraryLoader interface.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/testing/SignatureSubject.kt
src/main/kotlin/org/wfanet/measurement/common/testing/CommandLineTesting.kt

These were introduced when the Truth version was upgraded in #268.

fix: Address compile warnings on custom Truth subjects

---

src/main/kotlin/org/wfanet/measurement/storage/testing/BlobSubject.kt

fix: Address build warning for BlobSubject

---

src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt

feat: Add gRPC reflection service to CommonServer

---

src/main/kotlin/org/wfanet/measurement/storage/SelectedStorageClient.kt
src/test/kotlin/org/wfanet/measurement/storage/SelectedStorageClientTest.kt

parseBlobUri will be useful for consumers of the class

expose parseBlobUri from SelectedStorageClient companion object

---

src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt

BREAKING CHANGE: This removes the --grpc-thread-pool-size option
Issue: world-federation-of-advertisers/cross-media-measurement#2380

fix!: Use direct executor for gRPC server in CommonServer

---

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt

Issue: https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/2376

fix: Ensure that Spanner AsyncResultSet is cancelled on coroutine cancellation

---

src/main/kotlin/org/wfanet/measurement/common/ProtoReflection.kt
src/main/proto/wfa/measurement/common/testing/depends_on_simple.proto
src/test/kotlin/org/wfanet/measurement/common/ProtoReflectionTest.kt

Issue: world-federation-of-advertisers/cross-media-measurement#2728

feat: Add ProtoReflection.getFieldsRecursive
