world-federation-of-advertisers/common-jvm

build/com_google_protobuf/repo.bzl
build/common_jvm_maven.bzl
build/kt_jvm_proto_library.bzl
src/test/kotlin/org/wfanet/bazel/BUILD.bazel
src/test/kotlin/org/wfanet/bazel/KtJvmProtoLibraryTest.kt
src/test/proto/wfa/measurement/common/BUILD.bazel
src/test/proto/wfa/measurement/common/fake_message.proto

This should eventually be owned by rules_kotlin (https://github.com/bazelbuild/rules_kotlin).
This initial PR contains some minor hacks that future PRs will address before attempting to move this over to rules_kotlin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/26)

Add kt_jvm_proto_library BUILD rule.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/crypto/InvalidSignatureException.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/Signatures.kt
src/main/kotlin/org/wfanet/measurement/storage/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/storage/VerifiedStorageExtensions.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/crypto/SignaturesTest.kt

X509Certificate.verifySignature(signedData: SignedData) will
remain in consent-signaling-client as it is only used internally
in that repo and uses a repo-specific proto.
Tests migrated as well.
Followup PR to move the references.
Note that the extensions to StorageClient and
StorageClient.Blob are kept in a separate location to avoid
depending on the signing code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/34)

Migrate Signatures to common-jvm from consent-signaling-client

---

src/main/kotlin/org/wfanet/measurement/common/graphviz/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/graphviz/Dot.kt
src/test/kotlin/org/wfanet/measurement/common/graphviz/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/graphviz/DotTest.kt

This can be used for visualizing the status of panelist lookup protocols and multi-party computations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/40)

Add GraphViz Kotlin DSL

---

src/main/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/crypto/Hashing.kt

This also adds a hashing Flow operator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/52)

Avoid unnecessary byte array copies when computing SHA-256 hash.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/storage/BUILD.bazel

- add dependencies to protobuf and kotlinx where needed, rather than
relying on indirect imports
- move PemIo into signing storage as it has internal methods only used
there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/63)

change dependencies to more direct paths

---

build/defs.bzl
build/kt_jvm_proto/BUILD.bazel
build/kt_jvm_proto/defs.bzl
build/kt_jvm_proto/extract_srcjars.sh
src/main/proto/google/type/BUILD.bazel
src/test/proto/wfa/measurement/common/BUILD.bazel

This uses Bazel aspects to bring kt_jvm_proto_library in line with other language-specific _proto_library rules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/66)

Update kt_jvm_proto_library to handle transitive deps.

---

imports/kotlin/com/google/protobuf/kotlin/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/Bytes.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/Hashing.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/Signatures.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/SignedBlob.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt
src/main/kotlin/org/wfanet/measurement/storage/testing/AbstractStorageClientTest.kt

com.google.protobuf.kotlin.toByteString should be used instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/75)

Mark org.wfanet.measurement.common.toByteString as deprecated.

---

src/main/kotlin/org/wfanet/measurement/common/Base64.kt
src/main/kotlin/org/wfanet/measurement/common/Bytes.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/PemIo.kt
src/main/kotlin/org/wfanet/measurement/common/identity/Identifiers.kt
src/test/kotlin/org/wfanet/measurement/common/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/Base64Test.kt
src/test/kotlin/org/wfanet/measurement/common/BytesTest.kt
src/test/kotlin/org/wfanet/measurement/common/identity/IdentifiersTest.kt

This technically makes a "breaking" change by swapping the return type of String.base64UrlEncode, but all known calls should be unaffected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/74)

Add base64 encoding conversions for ByteString and Long.

---

src/main/kotlin/org/wfanet/measurement/aws/s3/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/testing/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/testing/FakeKmsClient.kt
src/main/kotlin/org/wfanet/measurement/storage/testing/AbstractStorageClientTest.kt
src/main/kotlin/org/wfanet/measurement/storage/testing/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/storage/testing/InMemoryStorageClient.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClientTest.kt
src/test/kotlin/org/wfanet/measurement/storage/testing/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/storage/testing/InMemoryStorageClientTest.kt

This also adds tests for `KmsStorageClient` and `InMemoryStorageClient`, and uses the blob key as the associated data for KMS AEAD.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/73)

Fix KmsStorageClient.createBlob returning encrypted wrapped blob.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KeyHandle.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/85)
https://rally1.rallydev.com/#/?detail=/task/623033865659&fdp=true

Ensure Tink Hybrid encryption primitives are registered before decrypting.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/SigningCerts.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/testing/SigningCertsTesting.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/TlsFlags.kt
src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageServer.kt
src/main/kotlin/org/wfanet/measurement/storage/forwarded/ForwardedStorageFromFlags.kt

This also fixes a warning in the ForwardedStorage service implementation.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/84)
https://rally1.rallydev.com/#/?detail=/task/623033745469&fdp=true

Use TLS channel for ForwardedStorage client.

---

build/kt_jvm_proto/defs.bzl
build/macros.bzl
src/main/kotlin/org/wfanet/measurement/storage/filesystem/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/storage/forwarded/BUILD.bazel
src/main/proto/wfa/measurement/internal/testing/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/grpc/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/storage/filesystem/BUILD.bazel
src/test/proto/wfa/measurement/common/BUILD.bazel

This renames the macro from kt_jvm_grpc_and_java_proto_library to kt_jvm_grpc_proto_library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/89)

Include kt_jvm_proto_library in Kotlin gRPC macro.

---

src/main/kotlin/org/wfanet/measurement/aws/s3/S3StorageClient.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/SignedBlob.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClient.kt
src/main/kotlin/org/wfanet/measurement/gcloud/gcs/GcsStorageClient.kt
src/main/kotlin/org/wfanet/measurement/storage/StorageClient.kt
src/main/kotlin/org/wfanet/measurement/storage/Store.kt
src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageClient.kt
src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageService.kt
src/main/kotlin/org/wfanet/measurement/storage/forwarded/ForwardedStorageClient.kt
src/main/kotlin/org/wfanet/measurement/storage/testing/AbstractStorageClientTest.kt
src/main/kotlin/org/wfanet/measurement/storage/testing/InMemoryStorageClient.kt
src/main/proto/wfa/measurement/internal/testing/forwarded_storage_service.proto
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClientTest.kt
src/test/kotlin/org/wfanet/measurement/storage/testing/InMemoryStorageClientTest.kt

This renames StorageClient.createBlob to writeBlob, changing the documented semantics. Note that some StorageClient implementations such as GcsStorageClient already followed these semantics.
This more closely matches some of our current usage patterns w.r.t. handling incomplete writes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/90)
https://rally1.rallydev.com/#/?detail=/task/625602196713&fdp=true

Allow overwriting blob content.

---

src/main/kotlin/org/wfanet/measurement/common/crypto/tink/testing/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/testing/FakeKmsClient.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/KmsStorageClientTest.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/testing/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/testing/FakeKmsClientTest.kt

The method was incorrectly returning whether the key URI scheme is supported in general rather than whether the specific key URI is supported by the instance.
This also adds a register method to the companion object to parallel GcpKmsClient.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/100)

Fix behavior of FakeKmsClient.doesSupport.

---

src/main/kotlin/org/wfanet/measurement/common/Bytes.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/crypto/DerEncoding.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/SecurityProviderTest.kt

This includes a slight behavioral change to the subjectKeyIdentifier and authorityKeyIdentifier properties, where they will now throw an exception rather than returning null if parsing fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/102)

Parse SKID and AKID according to DER spec.

---

src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageClient.kt
src/test/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageClientTest.kt

This is a backwards-incompatible change. Blobs written using the previous implementation of FileSystemStorageClient will not be able to be read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/105)

Store blobs on file system as if blob key were a Unix filesystem path.

---

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerDatabaseConnector.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerFlags.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/tools/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/tools/UpdateSchema.kt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/109)

Add tool library for updating Spanner schema using Liquibase.

---

src/main/kotlin/org/wfanet/measurement/common/HexString.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/SigningKeyHandle.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/SigningKeyStore.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/crypto/SigningKeyStoreTest.kt

SigningKeyStore initializes its private Store implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/103)

Take in StorageClient instead of Store in SigningKeyStore constructor.

---

build/common_jvm_maven.bzl
imports/kotlin/io/grpc/kotlin/BUILD.bazel

GRPC_KOTLIN_OVERRIDE_TARGETS was not being included in the final override targets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/145)

Fix duplicate definition of grpc-kotlin stub library.

---

build/kotlinx_coroutines/repo.bzl
imports/kotlin/kotlinx/coroutines/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/gcloud/common/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt

Reverts world-federation-of-advertisers/common-jvm#150
Rollback reason: Introduces potential deadlocks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/155)

Revert "Remove runBlocking usage in Spanner AsyncDatabaseClient."

---

build/common_jvm_maven.bzl
build/grpc_java/repo.bzl
build/rules_proto/repo.bzl
build/versions.bzl
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerDatabaseConnector.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/SpannerEmulatorDatabaseRule.kt

Limiting to a single transaction when using Spanner Emulator was masking an issue related to the Spanner client library's internal transaction retry logic. Aborted transactions should be retried[^1], but coroutine cancellation could prevent this from occurring.
[^1]: https://cloud.google.com/spanner/docs/transactions
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/162)

Fix potential deadlock in Spanner AsyncDatabaseClient.

---

src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/ErrorLoggingServerInterceptor.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/LoggingClientInterceptor.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/LoggingServerInterceptor.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/testing/GrpcTestServerRule.kt

* Include a request ID.
* Log when an RPC is completed, as there is otherwise no indicator of such if an RPC has an empty response.
* Unconditionally log severe RPC errors on the server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/164)

Update gRPC logging to include more information.

---

build/common_jvm_maven.bzl
src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerDatabaseConnector.kt

Breaking API change: TransactionWork no longer takes a TransactionContext parameter, and instead is run with a TransactionScope receiver. This TransactionScope extends CoroutineScope so that CoroutineScope extension functions called from TransactionWork will be run in the TransactionScope.
This also drops the unnecessary transaction timeout, instead expecting callers to implement their own timeouts as necessary.
This is for world-federation-of-advertisers/cross-media-measurement#840
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/179)

Restructure coroutine scopes for Spanner transactions.

---

.github/workflows/build-test.yml

18.04 is being turned down 2023-04-01 and will be offline on and off until then.

Update the build/test environment to 20.04

---

build/io_bazel_rules_docker/base_images.bzl
build/io_bazel_rules_docker/repo.bzl
build/versions.bzl

This also updates the base Distroless Java images to the latest release.

Update rules_docker to 0.25.0.

---

build/common_jvm_extra_deps.bzl
build/grpc_extra_deps.bzl

In the CMM repo, we want to add a GRPC Gateway for the BFF Reporting API to support the Reporting UI. GRPC Gateway requires to call `go_register_toolchains(version = "1.19.4")`. Or at least trying to change things to support the hardcoded version in the dependency would be difficult. The rest of the file is the same to minimize the risk of breaking anything.

Pulling out grpc_extra_deps and updating the go_register_toolchains version

---

build/common_jvm_deps.bzl
build/common_jvm_extra_deps.bzl
build/versions.bzl

This also updates rules_jvm_external to 5.2.

Add deps and extra deps for rules_jvm_external.

---

src/main/kotlin/org/wfanet/measurement/common/Bytes.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/Hashing.kt
src/test/kotlin/org/wfanet/measurement/common/BytesTest.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/HashingTest.kt

This also moves non-extension hashing functions into a `Hashing` object per the style guide. The top-level versions are marked as deprecated.

Add byteOrder param to functions that convert between Longs and bytes.

---

src/main/kotlin/org/wfanet/measurement/common/CommandLines.kt
src/main/kotlin/org/wfanet/measurement/common/testing/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/testing/CommandLineTesting.kt
src/test/kotlin/org/wfanet/measurement/common/testing/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/testing/CommandLineTestingTest.kt

This addresses a bug where command line tests may appear to pass without actually running any tests. This results in breaking changes to the CommandLineTesting util.

Do not call exitProcess from commandLineMain on non-zero status.

---

build/io_bazel_rules_docker/base_images.bzl

This picks up a fix for CVE-2023-21930.

Update Java base images.

---

build/common_jvm_maven.bzl

This updates Postgres dependencies to avoid world-federation-of-advertisers/cross-media-measurement#1410

Update Postgres dependencies for Google Cloud SQL

---

.bazelrc
MODULE.bazel
MODULE.bazel.lock

This also means updating the build to use JDK 17.
Closes #213

Update Distroless Java base images to java17-debian12.

---

.bazelrc
BUILD.bazel
MODULE.bazel
MODULE.bazel.lock
build/rules_kotlin/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/grpc/testing/Mocking.kt

build!: Upgrade Mockito to v5
The capability to mock final methods is added in v5, which is necessary for testing in some cases. This does, however, add the requirement to target jvm version 11.
BREAKING CHANGE: Targets Java 11
To migrate to this commit, the .bazelrc file needs to include "build --java_language_version=11". If a version of this already exists that targets an older language version, update it to target 11. Otherwise, add the line.

build!: Upgrade Mockito to v5

---

.github/workflows/build-test.yml
MODULE.bazel.lock

fix: Add lockfile check to presubmit workflow

fix: Add lockfile check to presubmit workflow

---

build/openssl/generate_root_certificate_validator.sh
build/openssl/generate_user_certificate_validator.sh

The subject output appears to have changed in more recent OpenSSL versions, but the hash algorithm has been stable since OpenSSL 1.0.0.

fix: Use subject hash for openssl macro test

---

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/SpannerEmulatorDatabaseRule.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/SpannerEmulatorRule.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/UsingSpannerEmulator.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/testing/macros.bzl
src/test/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClientTest.kt
src/test/kotlin/org/wfanet/measurement/gcloud/spanner/BUILD.bazel

The Spanner emulator documentation recommends this. It should hopefully reduce test flakiness.
BREAKING CHANGE: The `SpannerEmulatorDatabaseRule` constructor has a new required parameter of type `SpannerDatabaseAdmin`.

refactor!: Share single Spanner emulator process

---

src/main/kotlin/org/wfanet/measurement/gcloud/common/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/gcloud/common/Futures.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerDatabaseConnector.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerFlags.kt

The `AsyncRunner` implementation apparently runs blocking code in a separate thread. This changes `AsyncDatabaseClient` to wrap `AsyncTransactionManager` instead.
BREAKING CHANGE: `AsyncDatabaseClient` no longer takes an `Executor` for read/write transactions
BREAKING CHANGE: Unused flags for building the read/write transaction `Executor` have been removed from `SpannerFlags`
BREAKING CHANGE: `TransactionWork` no longer has a `CoroutineScope` receiver.

fix!: Make Spanner AsyncDatabaseClient read/write transactions actually asynchronous

---

src/main/kotlin/org/wfanet/measurement/common/grpc/OpenIdConnectAuthentication.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/testing/OpenIdProvider.kt
src/test/kotlin/org/wfanet/measurement/common/grpc/OpenIdConnectAuthenticationTest.kt

This addresses a bug in #288 
The client ID is generated by the OpenID provider on registration, so the OpenID provider configuration needs to include the client ID.

fix!: Verify audience claim matches client ID for OpenID provider

---

src/main/kotlin/org/wfanet/measurement/common/grpc/OpenIdConnectAuthentication.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/testing/OpenIdProvider.kt
src/test/kotlin/org/wfanet/measurement/common/grpc/OpenIdConnectAuthenticationTest.kt

Reverts world-federation-of-advertisers/common-jvm#290
The `aud` (audience) claim is only required to match the client ID for OpenID Connect (OIDC) ID Tokens. For authentication, the expectation is to use RFC 9068 Access Tokens where the audience is application-specific.

Revert "fix!: Verify audience claim matches client ID for OpenID provider"

---

src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt

Client auth was being turned off entirely instead.

fix: Make client auth optional when `--require-client-auth` is false

---

src/main/kotlin/org/wfanet/measurement/common/grpc/testing/OpenIdProvider.kt
src/test/kotlin/org/wfanet/measurement/common/grpc/OpenIdConnectAuthenticationTest.kt

This allows OpenIdProvider to be used for integration tests which need a stable key.
This change also ensures that generated tokens include all required fields specified in RFC 9068.
BREAKING CHANGE: generateCredentials now takes a TTL Duration instead of an expiration Instant.

feat!: Allow private key to be specified to OpenIdProvider

---

src/main/kotlin/org/wfanet/measurement/common/grpc/OAuthTokenAuthentication.kt
src/test/kotlin/org/wfanet/measurement/common/grpc/OAuthTokenAuthenticationTest.kt

This is mandated by Section 4 of RFC 9068.

fix: Include error code in JWT access token validation messages

---

src/main/kotlin/org/wfanet/measurement/storage/MesosRecordIoStorageClient.kt
src/main/proto/wfa/measurement/storage/testing/BUILD.bazel
src/main/proto/wfa/measurement/storage/testing/complex_message.proto
src/test/kotlin/org/wfanet/measurement/storage/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/storage/MesosRecordIoStorageClientTest.kt

We saw the mesos storage client fail with complex message types. 
I believe the error occurred because the prior code converts everything to a String and that isn't always possible with the underlying data.
Note that the new added test hangs with the old code but now succeeds.

fix mesos storage client

---

src/main/kotlin/org/wfanet/measurement/common/ClassLoaderResources.kt

This is needed by TEE apps that don't have access to resources and need them bundled in the jar.

add getResourceJarFile

---

.github/workflows/build-test.yml
.github/workflows/lint.yml

ubuntu-20.04 has been turned down, so workflows using it cannot run.

ci: Update workflows to run on ubuntu-22.04

---

src/main/kotlin/org/wfanet/measurement/common/Instrumentation.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/CommonServer.kt
src/test/kotlin/org/wfanet/measurement/common/InstrumentationTest.kt
src/test/kotlin/org/wfanet/measurement/common/grpc/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/grpc/TransportSecurityTest.kt

In particular, do not shut down the gRPC server executor explicitly prior to the grace period.
RELNOTES: gRPC servers now support a grace period to allow in-flight RPCs to complete when shutting down. This can be controlled by the `--shutdown-grace-period-seconds` option.
BREAKING CHANGE: `Instrumentation.instrumentThreadPool` returns a handle for cleanup instead of an `ExecutorService` that cleans up on shutdown.

feat!: Allow a grace period for in-flight RPCs to complete

---

src/main/kotlin/org/wfanet/measurement/common/grpc/BUILD.bazel
src/main/kotlin/org/wfanet/measurement/common/grpc/Channel.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/ServiceConfig.kt
src/main/kotlin/org/wfanet/measurement/common/grpc/testing/GrpcTestServerRule.kt

This retries on UNAVAILABLE status with backoff and includes a deadline.
BREAKING CHANGE: The `defaultServiceConfig` param for building channels now takes a `ServiceConfig` object instead of a map.

feat!: Include a default ServiceConfig for all gRPC channels

---

src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/WithEnvelopeEncryption.kt

`val handle: KeysetHandle =
TinkProtoKeysetFormat.parseEncryptedKeyset(encryptedDek.toByteArray(), kekAead, byteArrayOf())`
errors `Unsupported Key Type: LegacyProtoKey`.
That happens because the `StreamingAeadConfig` is registered after the parser generates the `KeysetHandle`. So the parses fallback to `LegacyProto` which is not supported.
This PR fixes the problem by registering the Config before the parser runs.

fix: register aeadconfig before parsing

---

src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerDatabaseConnector.kt
src/main/kotlin/org/wfanet/measurement/gcloud/spanner/SpannerFlags.kt

This allows redefinitions of the same flags, for example without making them required.

refactor: Extract SpannerParams interface from SpannerFlags

---

src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingEncryption.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingEncryptionTest.kt

This is for the DataProvider Requisition client library, where the input is expected to be an entire frequency vector.
Issue: world-federation-of-advertisers/cross-media-measurement#2593

feat: Add StreamingEncryption util with encryptChunked method

---

src/main/kotlin/org/wfanet/measurement/common/Bytes.kt
src/main/kotlin/org/wfanet/measurement/common/CoroutineReadableByteChannel.kt
src/main/kotlin/org/wfanet/measurement/common/CoroutineWritableByteChannel.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/BufferedPipe.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingAeadStorageClient.kt
src/main/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingEncryption.kt
src/test/kotlin/org/wfanet/measurement/common/CoroutineWritableByteChannelTest.kt
src/test/kotlin/org/wfanet/measurement/common/crypto/tink/StreamingEncryptionTest.kt

This removes the workaround of relying on the default channel buffer to ensure that all bytes are written to the underlying coroutine channel by the time the encrypting channel is closed.
BREAKING-CHANGE: CoroutineWritableByteChannel no longer has a public constructor. Instances must instead be created via factory functions.
BREAKING-CHANGE: The StreamingEncryption.encryptChunked signature has changed to mirror the StreamingAead.encrypt signature. In particular, the associatedData param no longer has a default value.
Issue: world-federation-of-advertisers/cross-media-measurement#2594

fix!: Ensure that StreamingAeadStorageClient writes all bytes
